//
//  NamesArrays.swift
//  Mega Genrot
//
//  Created by Oran Levi on 06/10/2022.
//

import Foundation

//MARK: - Names Arrays

var maleNames = ["Rigoberto", "Alphonso", "Ty", "Shelby", "Rickie", "Noe", "Vern", "Bobbie", "Reed", "Jefferson", "Elvis", "Bernardo", "Mauricio", "Hiram", "Donovan", "Basil", "Riley", "Ollie", "Nickolas", "Maynard", "Scot", "Vince", "Quincy", "Eddy", "Sebastian", "Federico", "Ulysses", "Heriberto", "Donnell", "Cole", "Denny", "Davis", "Gavin", "Emery", "Ward", "Romeo", "Jayson", "Dion", "Dante", "Clement", "Coy", "Odell", "Maxwell", "Jarvis", "Bruno", "Issac", "Mary", "Dudley", "Brock", "Sanford", "Colby", "Carmelo", "Barney", "Nestor", "Hollis", "Stefan", "Donny", "Art", "Linwood", "Beau", "Weldon", "Galen", "Isidro", "Truman", "Delmar", "Johnathon", "Silas", "Frederic", "Dick", "Kirby", "Irwin", "Cruz", "Merlin", "Merrill", "Charley", "Marcelino", "Lane", "Harris", "Cleo", "Carlo", "Trenton", "Kurtis", "Hunter", "Aurelio", "Winfred", "Vito", "Collin", "Denver", "Carter", "Leonel", "Emory", "Pasquale", "Mohammad", "Mariano", "Danial", "Blair", "Landon", "Dirk", "Branden", "Adan", "Numbers", "Clair", "Buford", "German", "Bernie", "Wilmer", "Joan", "Emerson", "Zachery", "Fletcher", "Jacques", "Errol", "Dalton", "Monroe", "Josue", "Dominique", "Edwardo", "Booker", "Wilford", "Sonny", "Shelton", "Carson", "Theron", "Raymundo", "Daren", "Tristan", "Houston", "Robby", "Lincoln", "Jame", "Genaro", "Gale", "Bennett", "Octavio", "Cornell", "Laverne", "Hung", "Arron", "Antony", "Herschel", "Alva", "Giovanni", "Garth", "Cyrus", "Cyril", "Ronny", "Stevie", "Lon", "Freeman", "Erin", "Duncan", "Kennith", "Carmine", "Augustine", "Young", "Erich", "Chadwick", "Wilburn", "Russ", "Reid", "Myles", "Anderson", "Morton", "Jonas", "Forest", "Mitchel", "Mervin", "Zane", "Rich", "Jamel", "Lazaro", "Alphonse", "Randell", "Major", "Johnie", "Jarrett", "Brooks", "Ariel", "Abdul", "Dusty", "Luciano", "Lindsey", "Tracey", "Seymour", "Scottie", "Eugenio", "Mohammed", "Sandy", "Valentin", "Chance", "Arnulfo", "Lucien", "Ferdinand", "Thad", "Ezra", "Sydney", "Aldo", "Rubin", "Royal", "Mitch", "Earle", "Abe", "Wyatt", "Marquis", "Lanny", "Kareem", "Jamar", "Boris", "Isiah", "Emile", "Elmo", "Aron", "Leopoldo", "Everette", "Josef", "Gail", "Eloy", "Dorian", "Rodrick", "Reinaldo", "Lucio", "Jerrod", "Weston", "Hershel", "Barton", "Parker", "Lemuel", "Lavern", "Burt", "Jules", "Gil", "Eliseo", "Ahmad", "Nigel", "Efren", "Antwan", "Alden", "Margarito", "Coleman", "Refugio", "Dino", "Osvaldo", "Les", "Deandre", "Normand", "Kieth", "Ivory", "Andrea", "Norberto", "Napoleon", "Jerold", "Fritz", "Rosendo", "Milford", "Sang", "Deon", "Christoper", "Alfonzo", "Lyman", "Josiah", "Brant", "Wilton", "Rico", "Jamaal", "Dewitt", "Carol", "Brenton", "Yong", "Olin", "Foster", "Faustino", "Claudio", "Judson", "Gino", "Edgardo", "Berry", "Alec", "Tanner", "Jarred", "Donn", "Trinidad", "Tad", "Shirley", "Prince", "Porfirio", "Odis", "Maria", "Lenard", "Chauncey", "Chang", "Tod", "Mel", "Marcelo", "Kory", "Augustus", "Keven", "Hilario", "Bud", "Sal", "Rosario", "Orval", "Mauro", "Dannie", "Zachariah", "Olen", "Anibal", "Milo", "Jed", "Frances", "Thanh", "Dillon", "Amado", "Newton", "Connie", "Lenny", "Tory", "Richie", "Lupe", "Horacio", "Brice", "Mohamed", "Delmer", "Dario", "Reyes", "Dee", "Mac", "Jonah", "Jerrold", "Robt", "Hank", "Sung", "Rupert", "Rolland", "Kenton", "Damion", "Chi", "Antone", "Waldo", "Fredric", "Bradly", "Quinn", "Kip", "Burl", "Walker", "Tyree", "Jefferey", "Ahmed", "Willy", "Stanford", "Oren", "Noble", "Moshe", "Mikel", "Enoch", "Brendon", "Quintin", "Jamison", "Florencio", "Darrick", "Tobias", "Minh", "Hassan", "Giuseppe", "Demarcus", "Cletus", "Tyrell", "Lyndon", "Keenan", "Werner", "Theo", "Geraldo", "Lou", "Columbus", "Chet", "Bertram", "Markus", "Huey", "Hilton", "Dwain", "Donte", "Tyron", "Omer", "Isaias", "Hipolito", "Fermin", "Chung", "Adalberto", "Valentine", "Jamey", "Bo", "Barrett", "Whitney", "Teodoro", "Mckinley", "Maximo", "Garfield", "Sol", "Raleigh", "Lawerence", "Abram", "Rashad", "King", "Emmitt", "Daron", "Chong", "Samual", "Paris", "Otha", "Miquel", "Lacy", "Eusebio", "Dong", "Domenic", "Darron", "Buster", "Antonia", "Wilber", "Renato", "Jc", "Hoyt", "Haywood", "Ezekiel", "Chas", "Florentino", "Elroy", "Clemente", "Arden", "Neville", "Kelley", "Edison", "Deshawn", "Carrol", "Shayne", "Nathanial", "Jordon", "Danilo", "Claud", "Val", "Sherwood", "Raymon", "Rayford", "Cristobal", "Ambrose", "Titus", "Hyman", "Felton", "Ezequiel", "Erasmo", "Stanton", "Lonny", "Len", "Ike", "Milan", "Lino", "Jarod", "Herb", "Andreas", "Walton", "Rhett", "Palmer", "Jude", "Douglass", "Cordell", "Oswaldo", "Ellsworth", "Virgilio", "Toney", "Nathanael", "Del", "Britt", "Benedict", "Mose", "Hong", "Leigh", "Johnson", "Isreal", "Gayle", "Garret", "Fausto", "Asa", "Arlen", "Zack", "Warner", "Modesto", "Francesco", "Manual", "Jae", "Gaylord", "Gaston", "Filiberto", "Deangelo", "Michale", "Granville", "Wes", "Malik", "Zackary", "Tuan", "Nicky", "Eldridge", "Cristopher", "Cortez", "Antione", "Malcom", "Long", "Korey", "Jospeh", "Colton", "Waylon", "Von", "Hosea", "Shad", "Santo", "Rudolf", "Rolf", "Rey", "Renaldo", "Marcellus", "Lucius", "Lesley", "Kristofer", "Boyce", "Benton", "Man", "Kasey", "Jewell", "Hayden", "Harland", "Arnoldo", "Rueben", "Leandro", "Kraig", "Jerrell", "Jeromy", "Hobert", "Cedrick", "Arlie", "Winford", "Wally", "Patricia", "Luigi", "Keneth", "Jacinto", "Graig", "Franklyn", "Edmundo", "Sid", "Porter", "Leif", "Lauren", "Jeramy", "Elisha", "Buck", "Willian", "Vincenzo", "Shon", "Michal", "Lynwood", "Lindsay", "Jewel", "Jere", "Hai", "Elden", "Dorsey", "Darell", "Broderick", "Alonso"]

var femaleNames = ["Adah", "Adam", "Adena", "Adrien", "Agnus", "Agripina", "Agueda", "Ai", "Aide", "Aiko", "Ailene", "Akilah", "Alaine", "Alane", "Alayna", "Albert", "Aleen", "Aleisha", "Alessandra", "Alfredia", "Alleen", "Allena", "Allyn", "Alona", "Alverta", "Alysa", "Amal", "Amee", "Amiee", "Amira", "An", "Analisa", "Anamaria", "Andera", "Angelyn", "Angila", "Angla", "Anisa", "Anisha", "Anja", "Anjelica", "Annamaria", "Annelle", "Annika", "Annita", "Antonetta", "Ardath", "Ardelia", "Ardelle", "Argentina", "Arica", "Arlean", "Arlinda", "Arlyne", "Armandina", "Arnette", "Ashanti", "Ashlea", "Asley", "Audria", "Audrie", "Aurore", "Austin", "Avery", "Avril", "Ayako", "Azalee", "Azzie", "Bao", "Barabara", "Bari", "Barrie", "Basilia", "Beata", "Beatris", "Beaulah", "Bebe", "Bee", "Belkis", "Berna", "Bernarda", "Bernardina", "Berry", "Bethanie", "Bettyann", "Beula", "Bibi", "Billi", "Blake", "Blondell", "Bobette", "Bok", "Bong", "Brande", "Breana", "Brian", "Brittaney", "Brittanie", "Britteny", "Brittny", "Bruna", "Bryanna", "Buena", "Bula", "Bulah", "Bunny", "Burma", "Calandra", "Calista", "Camellia", "Camie", "Camila", "Cammy", "Candra", "Carita", "Carlee", "Carlena", "Carli", "Carlita", "Carlos", "Carmelia", "Carmina", "Carolin", "Caroll", "Caroyln", "Carry", "Carylon", "Casimira", "Cassaundra", "Cassey", "Cassi", "Cassondra", "Cassy", "Catherin", "Catherina", "Cathern", "Catheryn", "Catrice", "Cayla", "Cecille", "Celesta", "Celinda", "Celsa", "Chae", "Chan", "Chanell", "Chanelle", "Chang", "Chantay", "Chara", "Charis", "Charita", "Charlena", "Charlesetta", "Charlott", "Charlsie", "Charlyn", "Charmain", "Chasidy", "Chassidy", "Chere", "Cheree", "Cherelle", "Cherilyn", "Cherlyn", "Chia", "Chieko", "Christia", "Christinia", "Chu", "Cinderella", "Cindie", "Cira", "Clarence", "Claretha", "Claretta", "Clarinda", "Claris", "Clarisa", "Classie", "Claude", "Clelia", "Clemencia", "Cleotilde", "Clora", "Codi", "Colby", "Colene", "Collene", "Conception", "Concha", "Contessa", "Coralie", "Cordia", "Corrin", "Corrinne", "Creola", "Cris", "Crysta", "Crystle", "Cuc", "Curtis", "Cyndy", "Cyrstal", "Dagny", "Daina", "Daine", "Dakota", "Dalene", "Dan", "Dann", "Dannie", "Danyel", "Darcel", "Darcey", "Darlena", "Daysi", "Deadra", "Deandrea", "Debera", "Dede", "Deeanna", "Deedee", "Deedra", "Deetta", "Deja", "Delcie", "Delila", "Delmy", "Deloise", "Deloras", "Delorse", "Delsie", "Denae", "Denisse", "Denny", "Denyse", "Deon", "Deonna", "Despina", "Dia", "Dierdre", "Dinorah", "Dion", "Divina", "Dodie", "Dominica", "Domitila", "Donella", "Donette", "Dong", "Donnetta", "Donnette", "Doreatha", "Dorethea", "Doria", "Dorla", "Dorthey", "Dotty", "Drew", "Dulcie", "Dusti", "Dwana", "Earlie", "Edra", "Edris", "Edyth", "Ehtel", "Eilene", "Ela", "Eladia", "Elane", "Elene", "Eleonor", "Eleonora", "Eleonore", "Elfreda", "Elfrieda", "Elidia", "Elin", "Elina", "Elinore", "Eliz", "Elizabet", "Ellamae", "Ellan", "Ellena", "Elli", "Ellis", "Elmer", "Elsy", "Elwanda", "Elza", "Emelina", "Emeline", "Emely", "Emmaline", "Enda", "Eryn", "Estefana", "Etha", "Etsuko", "Ettie", "Eufemia", "Eugena", "Eulah", "Euna", "Eura", "Eusebia", "Eustolia", "Evelynn", "Evia", "Evita", "Ewa", "Fairy", "Fatimah", "Faviola", "Felicidad", "Fermina", "Fernande", "Fidela", "Fidelia", "Fleta", "Floria", "Florrie", "Francene", "Franchesca", "Fransisca", "Fred", "Fredda", "Fredricka", "Frida", "Gala", "Galina", "Gema", "Genesis", "Genevie", "Genevive", "Genna", "Genny", "Georgann", "Georgeann", "Georgeanna", "Georgiann", "Georgianne", "Gerald", "Gertrudis", "Ghislaine", "Gidget", "Gilberte", "Gilma", "Ginette", "Gita", "Giuseppina", "Glayds", "Glenn", "Golden", "Grazyna", "Gregory", "Gricelda", "Grisel", "Gwyneth", "Halley", "Han", "Harold", "Hassie", "Heidy", "Heike", "Helaine", "Herma", "Hermila", "Hertha", "Hiedi", "Hien", "Hisako", "Hsiu", "Hue", "Hwa", "Hyo", "Ileen", "Illa", "Iraida", "Isadora", "Isobel", "Ivey", "Izetta", "Izola", "Ja", "Jacelyn", "Jack", "Jackelyn", "Jackqueline", "Jacquetta", "Jacqui", "Jaimee", "Jalisa", "Jama", "Jame", "Jamee", "Jamika", "Janean", "Janella", "Jani", "Janiece", "January", "Janyce", "Jaquelyn", "Jaymie", "Jayna", "Jeanelle", "Jeanett", "Jeanice", "Jeannetta", "Jeffie", "Jeffrey", "Jenae", "Jenee", "Jeneva", "Jennell", "Jennine", "Jeremy", "Jerica", "Jerlene", "Jessia", "Jessika", "Jestine", "Jesusita", "Ji", "Jinny", "Joane", "Joaquina", "Joette", "Johanne", "Johnette", "Johnsie", "Joie", "Joline", "Jon", "Jone", "Jong", "Jonie", "Josefine", "Joshua", "Jovan", "Joya", "Jude", "Jule", "Julene", "Julieann", "Julietta", "Julio", "Junie", "Junko", "Justa", "Kai", "Kaleigh", "Kallie", "Kalyn", "Kamala", "Kamilah", "Kandra", "Kanesha", "Kanisha", "Kareen", "Karena", "Karima", "Karisa", "Karly", "Karlyn", "Karole", "Karoline", "Karry", "Kasha", "Kasi", "Katelin", "Katelynn", "Katerine", "Katharyn", "Katheleen", "Katherina", "Kathline", "Kathrin", "Kayce", "Kaycee", "Keeley", "Keila", "Keira", "Keith", "Keitha", "Kelsi", "Kemberly", "Kenda", "Kendal", "Kenia", "Kera", "Keren", "Kerstin", "Keturah", "Keva", "Khadijah", "Khalilah", "Kimbra", "Kimi", "Kina", "Kirstie", "Kit", "Kittie", "Kiyoko", "Kizzie", "Kortney", "Krishna", "Krissy", "Kristeen", "Kristle", "Krysten", "Krystin", "Krystina", "Kyoko", "Lacresha", "Ladawn", "Lael", "Lahoma", "Laine", "Lajuana", "Lakeesha", "Lakendra", "Lakenya", "Lakia", "Lakita", "Lamonica", "Lanelle", "Lang", "Lanie", "Lannie", "Lanora", "Laree", "Larita", "Larraine", "Lashandra", "Lashaun", "Lashaunda", "Lashawna", "Lashawnda", "Lashay", "Lashell", "Lashon", "Lasonya", "Latarsha", "Latoyia", "Lauralee", "Lauran", "Laurena", "Laurence", "Laurinda", "Lavelle", "Lavenia", "Laveta", "Lavona", "Lavone", "Lawrence", "Layne", "Lean", "Leanora", "Lecia", "Leena", "Leia", "Leida", "Leigha", "Lekisha", "Lelah", "Lenita", "Leo", "Leoma", "Leon", "Leonia", "Leonida", "Leontine", "Lesha", "Lester", "Letisha", "Lewis", "Lianne", "Libbie", "Lieselotte", "Lilli", "Lillia", "Lilliam", "Lilliana", "Lindsy", "Linn", "Lisabeth", "Lisandra", "Lizeth", "Logan", "Loise", "Londa", "Loralee", "Lorean", "Loreta", "Lorette", "Loria", "Lorilee", "Lorina", "Lorita", "Lorriane", "Lorrine", "Louetta", "Loura", "Lourie", "Love", "Lovetta", "Luanna", "Luba", "Luci", "Lucilla", "Ludivina", "Luetta", "Lurlene", "Lyndia", "Lynna", "Mabelle", "Madalene", "Maddie", "Madelaine", "Madelene", "Mafalda", "Magali", "Mahalia", "Maire", "Maisha", "Maisie", "Makeda", "Malena", "Malka", "Malorie", "Malvina", "Man", "Mandie", "Manie", "Many", "Mao", "Maragaret", "Maragret", "Marcelene", "Marcell", "Marcene", "Marchelle", "Mardell", "Marg", "Margene", "Margherita", "Margrett", "Margy", "Marhta", "Marianela", "Marica", "Maricruz", "Mariella", "Marielle", "Mariette", "Marin", "Marine", "Maris", "Marisha", "Marketta", "Marlin", "Marline", "Marquitta", "Marshall", "Marth", "Marvella", "Marvis", "Marx", "Maryanna", "Marybelle", "Maryetta", "Maryland", "Maryln", "Marylouise", "Marylynn", "Maryrose", "Matha", "Maurita", "Maxima", "Maximina", "Mayola", "Meda", "Melani", "Melania", "Melia", "Melida", "Melita", "Melodee", "Melodi", "Mercedez", "Merideth", "Merissa", "Merlyn", "Merrilee", "Merrill", "Mertie", "Micha", "Michaele", "Michelina", "Miesha", "Mikaela", "Mike", "Miki", "Milda", "Milly", "Ming", "Minta", "Mirella", "Misha", "Mistie", "Mitsue", "Mitsuko", "Miyoko", "Monet", "Monnie", "Moon", "Mora", "Moriah", "Muoi", "Myesha", "Myrl", "Myrta", "Na", "Nadene", "Naida", "Nakesha", "Nam", "Nancee", "Nancey", "Natacha", "Natalya", "Natisha", "Necole", "Neda", "Neely", "Neida", "Nenita", "Neomi", "Nery", "Nevada", "Ngan", "Nguyet", "Nicholle", "Nida", "Niesha", "Nisha", "Nobuko", "Nohemi", "Nu", "Nubia", "Oda", "Olene", "Olevia", "Olinda", "Onie", "Onita", "Oralee", "Oretha", "Oscar", "Otelia", "Ozell", "Ozie", "Pa", "Palmira", "Pamila", "Pamula", "Parthenia", "Pasty", "Paulene", "Paulita", "Paz", "Pearly", "Peg", "Pei", "Peter", "Petronila", "Phebe", "Phung", "Ping", "Pok", "Porsche", "Priscila", "Providencia", "Pura", "Quinn", "Quyen", "Rachal", "Raelene", "Raisa", "Ranee", "Raymonde", "Rea", "Reagan", "Reanna", "Rebecka", "Reena", "Refugia", "Regine", "Reginia", "Reita", "Rema", "Remona", "Renay", "Renda", "Renna", "Ressie", "Rheba", "Ria", "Ricarda", "Rickie", "Rima", "Riva", "Rivka", "Robbi", "Robbyn", "Robena", "Roberto", "Rochel", "Rolande", "Rory", "Rosamaria", "Roselee", "Roselia", "Rosena", "Rosenda", "Rosette", "Rosio", "Rossana", "Rossie", "Rosy", "Roy", "Royce", "Rozanne", "Rubi", "Russell", "Ruthanne", "Ruthe", "Ryann", "Sacha", "Sadye", "Sage", "Salley", "Samella", "Sammy", "Samuel", "Sana", "Sanda", "Sandee", "Sarai", "Saran", "Saturnina", "Sau", "Scottie", "Season", "See", "Seema", "Sena", "Senaida", "September", "Serafina", "Serita", "Setsuko", "Shae", "Shakia", "Shakita", "Shala", "Shalanda", "Shalon", "Shan", "Shanae", "Shandi", "Shanel", "Shaniqua", "Shantae", "Shantay", "Shantelle", "Shanti", "Shaquana", "Shaquita", "Sharan", "Sharda", "Sharell", "Sharice", "Sharie", "Sharika", "Sharilyn", "Sharmaine", "Sharolyn", "Shaunta", "Shaunte", "Shavonda", "Shawanna", "Shawnta", "Shayne", "Sheba", "Shenika", "Shenna", "Shera", "Sherell", "Sherice", "Sherill", "Sherise", "Sherlene", "Sherril", "Sheryll", "Shila", "Shiloh", "Shin", "Shizue", "Shizuko", "Shondra", "Shonta", "Shyla", "Sima", "Simonne", "Sina", "Sirena", "Sixta", "Soila", "Sol", "Somer", "Sona", "Sparkle", "Stacee", "Stasia", "Stefany", "Stepanie", "Stephania", "Stephnie", "Suanne", "Sulema", "Sumiko", "Sunday", "Sunni", "Suzi", "Ta", "Taina", "Tajuana", "Takako", "Tama", "Tambra", "Tammera", "Tandra", "Tandy", "Taneka", "Taren", "Tari", "Tarra", "Tashina", "Tatum", "Tatyana", "Taunya", "Tawna", "Tayna", "Tegan", "Teisha", "Telma", "Temika", "Tempie", "Temple", "Tenesha", "Teofila", "Teresia", "Terica", "Terina", "Terisa", "Terrell", "Terrilyn", "Theressa", "Thi", "Thomasena", "Tien", "Tiera", "Tifany", "Tiffaney", "Tijuana", "Tilda", "Timika", "Timothy", "Tinisha", "Tisa", "Tish", "Tobie", "Toccara", "Toi", "Tommye", "Tona", "Tonette", "Tonisha", "Tonita", "Tora", "Torie", "Torri", "Torrie", "Tory", "Toshia", "Tova", "Travis", "Treasa", "Treena", "Tu", "Tula", "Twanda", "Tyisha", "Tynisha", "Ula", "Ulrike", "Un", "Valene", "Valentine", "Valeri", "Valrie", "Vanetta", "Vania", "Vanna", "Vannesa", "Vashti", "Vasiliki", "Venetta", "Vennie", "Verline", "Vernia", "Vernon", "Veronika", "Veronique", "Vertie", "Vi", "Victor", "Victorina", "Viki", "Vinita", "Virgen", "Virgil", "Voncile", "Wan", "Wanetta", "Wava", "Wendie", "Wendolyn", "Wenona", "Wesley", "Whitley", "Wilhemina", "Willena", "Willetta", "Willodean", "Willow", "Winter", "Wynell", "Xenia", "Xiao", "Xuan", "Yaeko", "Yael", "Yahaira", "Yajaira", "Yasmine", "Yasuko", "Yelena", "Yer", "Yevette", "Yoshie", "Youlanda", "Yuette", "Yuki", "Yuonne", "Yuriko", "Yvone", "Zada", "Zana", "Zenia", "Zetta", "Zonia"]

var surname = ["Abarca", "Abdi", "Abdullah", "Abell", "Abney", "Abrego", "Aceves", "Ackley", "Agnew", "Aguiar", "Ahern", "Aiello", "Ainsworth", "Akin", "Alam", "Albers", "Albertson", "Alcorn", "Alejandro", "Allman", "Almaraz", "Almond", "Alvarenga", "Amaral", "Amezcua", "Ammons", "An", "Andre", "Angell", "Angelo", "Antoine", "Appel", "Araiza", "Archibald", "Archie", "Arguello", "Armijo", "Armour", "Armstead", "Arriola", "Arsenault", "Artis", "Asbury", "Ascencio", "Ashcraft", "Ashe", "Ashford", "Atchison", "Atwell", "Au", "Augustin", "Ault", "Autry", "Avelar", "Avina", "Back", "Backus", "Bader", "Badger", "Badillo", "Baeza", "Bahr", "Ballew", "Ballinger", "Bandy", "Bankston", "Bannister", "Baptiste", "Barahona", "Barboza", "Bare", "Barela", "Barnette", "Barnhill", "Barros", "Barrows", "Bartels", "Basham", "Basile", "Baskin", "Batchelor", "Batson", "Battaglia", "Batten", "Battles", "Batts", "Bazan", "Beale", "Beall", "Bear", "Beattie", "Beckham", "Bedford", "Beeler", "Begley", "Belt", "Belton", "Bergstrom", "Berlin", "Bernhardt", "Bernier", "Berryman", "Bertram", "Bess", "Bethel", "Bettencourt", "Bianchi", "Bickel", "Bickford", "Biddle", "Binder", "Binkley", "Bittner", "Bivens", "Blackwood", "Blocker", "Blodgett", "Blunt", "Blythe", "Boatwright", "Bobbitt", "Bobo", "Bocanegra", "Bogan", "Bohannon", "Bohn", "Bolen", "Boling", "Bolt", "Bontrager", "Boothe", "Borders", "Boren", "Borja", "Bosch", "Bosley", "Boss", "Bostick", "Bounds", "Bourne", "Bourque", "Bowens", "Bracken", "Bradbury", "Brandenburg", "Brannan", "Bratcher", "Bratton", "Breedlove", "Brent", "Bricker", "Brill", "Bristol", "Bristow", "Brittain", "Brogan", "Brownell", "Broyles", "Brumley", "Bucher", "Buchholz", "Buckingham", "Budd", "Buffington", "Buford", "Bunker", "Bunting", "Burchett", "Burkhardt", "Burley", "Burney", "Burnside", "Burrow", "Buss", "Bussey", "Button", "Buxton", "Cable", "Cade", "Cady", "Cai", "Calabrese", "Caldera", "Calkins", "Calvin", "Camara", "Camargo", "Canada", "Canady", "Candelaria", "Canty", "Card", "Carden", "Carnahan", "Carpio", "Carreno", "Cartagena", "Casanova", "Casarez", "Cass", "Cassell", "Castanon", "Casteel", "Castellon", "Castleberry", "Casto", "Caswell", "Catalano", "Cathey", "Cato", "Caudle", "Cave", "Cedeno", "Cha", "Chaffin", "Chamberlin", "Chaves", "Chavira", "Chestnut", "Chew", "Chi", "Chiang", "Ching", "Chism", "Choe", "Chou", "Christ", "Clanton", "Clapp", "Clarkson", "Clausen", "Clegg", "Clem", "Clemente", "Clemmons", "Close", "Clough", "Clouse", "Cloutier", "Coble", "Cochrane", "Cockrell", "Coffin", "Coggins", "Cohn", "Colin", "Collado", "Collett", "Colley", "Colson", "Comeaux", "Conaway", "Cone", "Conlon", "Conover", "Conte", "Coombs", "Coons", "Coppola", "Cordell", "Cornish", "Coronel", "Cosgrove", "Counts", "Cousins", "Couture", "Covert", "Covey", "Craddock", "Cranford", "Creamer", "Creel", "Creighton", "Criswell", "Crites", "Cromer", "Cromwell", "Cruse", "Crutchfield", "Cupp", "Curiel", "Curtin", "Cushman", "Dabney", "Dagostino", "Dallas", "Damian", "Damon", "Damron", "Dangelo", "Das", "Davey", "Dayton", "Deanda", "Deangelis", "Deangelo", "Deboer", "Dell", "Dellinger", "Deloach", "Delrio", "Delrosario", "Deltoro", "Demers", "Deng", "Denham", "Denning", "Derosa", "Derr", "Derrick", "Desimone", "Desmond", "Destefano", "Deutsch", "Devito", "Deyoung", "Diallo", "Dimas", "Dion", "Dix", "Dodds", "Doe", "Doll", "Donato", "Donley", "Doucette", "Dover", "Drayton", "Driggers", "Du", "Dube", "Duckett", "Dugger", "Dunne", "Dupre", "Dupuis", "Duque", "Durand", "Durkin", "Duval", "Dvorak", "Dykstra", "Eads", "Eagle", "Earle", "Earnest", "Easterling", "Eaves", "Echevarria", "Echeverria", "Eck", "Eden", "Edmond", "Eggers", "Ehlers", "Elliot", "Embry", "Encarnacion", "Enos", "Enright", "Erb", "Ethridge", "Etienne", "Evangelista", "Evers", "Everson", "Fahey", "Fain", "Fairbanks", "Faircloth", "Faison", "Falcone", "Falls", "Fan", "Farrington", "Favela", "Fazio", "Feeney", "Feller", "Fellows", "Fenner", "Ferrari", "Ferro", "Fiedler", "Fincher", "Findley", "Fiore", "Fisk", "Fitzsimmons", "Flanders", "Flanigan", "Fleck", "Flick", "Flora", "Florence", "Fogarty", "Folsom", "Foltz", "Fontana", "Forster", "Forsyth", "Fort", "Fortier", "Fortin", "Frame", "Franke", "Frankel", "Frasier", "Frausto", "Frazer", "Fredericks", "Fredrickson", "Free", "Freed", "Freedman", "Freeland", "Freund", "Frick", "Fries", "Friesen", "Fryer", "Fu", "Fullerton", "Fulmer", "Fung", "Fuqua", "Furman", "Furr", "Fusco", "Gabel", "Gable", "Gaddis", "Gaddy", "Gagne", "Gainey", "Gaitan", "Galan", "Galbraith", "Galicia", "Gall", "Gallant", "Gantt", "Gaona", "Garman", "Garrido", "Garris", "Garrity", "Gaskin", "Gatewood", "Gayle", "Gearhart", "Geer", "Gerard", "Gerlach", "Germain", "Getz", "Geyer", "Giddens", "Gilbertson", "Gillen", "Gilley", "Gilson", "Gingerich", "Ginn", "Gladden", "Glasgow", "Glynn", "Goad", "Goble", "Goebel", "Goforth", "Goncalves", "Gonsalves", "Goodin", "Gooding", "Goolsby", "Gorham", "Gorski", "Gough", "Grabowski", "Gracia", "Grande", "Grasso", "Graziano", "Greathouse", "Greenlee", "Greiner", "Grice", "Griego", "Griffis", "Grijalva", "Grim", "Groff", "Guan", "Guenther", "Guess", "Guest", "Guffey", "Guido", "Gunther", "Gurley", "Gurrola", "Guyton", "Haag", "Haase", "Hackney", "Haddock", "Haggard", "Hague", "Hailey", "Hair", "Hales", "Hallman", "Halsey", "Halstead", "Hamblin", "Hammett", "Hammock", "Handley", "Hanes", "Hannan", "Harbin", "Harder", "Hardison", "Hardman", "Hargis", "Hargrave", "Harrelson", "Harry", "Harwell", "Hasan", "Haskell", "Hauck", "Haugen", "Hawes", "Hawks", "Hazel", "Hazen", "Headley", "Hecht", "Heckman", "Hedges", "Heflin", "Hefner", "Heil", "Heilman", "Heinrich", "Heinz", "Held", "Hendrick", "Henke", "Hennessey", "Hennessy", "Herbst", "Hermann", "Hernandes", "Herrin", "Hibbard", "Higdon", "Hildreth", "Himes", "Hintz", "Hitt", "Hofer", "Hofmann", "Hogg", "Hoke", "Holcombe", "Holloman", "Holly", "Holtz", "Homan", "Hoppe", "Horning", "Hornsby", "Horowitz", "Horst", "Houle", "Howland", "Hoy", "Hoyle", "Huey", "Hulsey", "Hundley", "Hung", "Huntington", "Huskey", "Hussein", "Hussey", "Hutchens", "Hutcheson", "Hutchings", "Hutto", "Hyland", "Hylton", "Hynes", "Ibanez", "Iniguez", "Irish", "Irons", "Irvine", "Isaacson", "Isbell", "Islas", "Ives", "Ivory", "Jablonski", "Jackman", "Jacoby", "Jamieson", "Janes", "Jang", "Jankowski", "Jaquez", "Jara", "Jasper", "Javier", "Jay", "Jeanbaptiste", "Jeffery", "Jenks", "Jenson", "Jerome", "Jester", "Jewett", "Jobe", "Joe", "Johansen", "Johnsen", "Johnstone", "Jolley", "Jonas", "Jorgenson", "Juan", "Jurado", "Kaye", "Keaton", "Kee", "Keefer", "Keel", "Keeling", "Keeney", "Keeton", "Kehoe", "Keim", "Keiser", "Kelleher", "Kelso", "Kersey", "Kester", "Ketchum", "Keyser", "Kidwell", "Kinard", "Kingsley", "Kingston", "Kirkwood", "Kirsch", "Kish", "Kling", "Klinger", "Knoll", "Knotts", "Knowlton", "Knudsen", "Knudson", "Koehn", "Koester", "Kohl", "Kohn", "Koss", "Kovach", "Kovacs", "Kozak", "Kraemer", "Kremer", "Kress", "Krug", "Kuehn", "Kuhns", "Kunkel", "Kunz", "Kuo", "Kuykendall", "Kwan", "Lacroix", "Lafleur", "Lagunas", "Landa", "Landon", "Langdon", "Langer", "Langlois", "Lanning", "Laplante", "Lapointe", "Laporte", "Lapp", "Larose", "Laster", "Lathrop", "Latimer", "Lavender", "Lavigne", "Lavoie", "Lawless", "Lazaro", "Lea", "Lear", "Lebron", "Leclair", "Ledezma", "Legg", "Lehmann", "Lei", "Leighton", "Leiva", "Lemaster", "Lemay", "Lemieux", "Leo", "Leong", "Lerner", "Leroy", "Levi", "Lew", "Liao", "Lieberman", "Lightfoot", "Lilley", "Lindgren", "Lindner", "Lindstrom", "Ling", "Linville", "Lister", "Littlefield", "Littleton", "Loftus", "Logue", "Lomax", "Loper", "Loredo", "Louie", "Lovato", "Lovejoy", "Loveless", "Loving", "Lowman", "Loy", "Loza", "Lozada", "Luce", "Lucio", "Luckett", "Luis", "Lum", "Lumpkin", "Lundberg", "Lundgren", "Lung", "Luster", "Luttrell", "Maas", "Macedo", "Mackay", "Macklin", "Maclean", "Macleod", "Madera", "Maestas", "Magallanes", "Magdaleno", "Magnuson", "Mahaffey", "Mahon", "Majors", "Maki", "Mancilla", "Mancuso", "Maness", "Mangum", "Manriquez", "Manson", "Manzanares", "Manzano", "Marek", "Mariano", "Mariscal", "Markley", "Marler", "Marquardt", "Marques", "Marquis", "Marte", "Martel", "Martines", "Martini", "Martinson", "Martz", "Matheny", "Mather", "Matheson", "Mathias", "Matteson", "Mattison", "Mauro", "Mayhew", "Mayorga", "Mazur", "Mazza", "Mccaffrey", "Mccallister", "Mccarter", "Mcclintock", "Mcclung", "Mccombs", "Mccool", "Mccorkle", "Mccreary", "Mccue", "Mcculloch", "Mccune", "Mccurry", "Mccutcheon", "Mcdade", "Mcdaniels", "Mcdevitt", "Mcdougal", "Mcewen", "Mcfall", "Mcfarlane", "Mcgrew", "Mcinnis", "Mckeever", "Mckelvey", "Mckenney", "Mckeon", "Mckeown", "Mckoy", "Mclaurin", "Mclendon", "Mcmichael", "Mcmurray", "Mcnabb", "Mcnutt", "Mcreynolds", "Mcvay", "Mcvey", "Mcwhorter", "Meeker", "Mei", "Meister", "Melchor", "Melgar", "Melo", "Menchaca", "Meneses", "Menjivar", "Meraz", "Mercier", "Merrell", "Merrick", "Merriman", "Mertz", "Michels", "Mickelson", "Milburn", "Miley", "Minnick", "Miramontes", "Moen", "Moll", "Molloy", "Molnar", "Monaco", "Monaghan", "Moncada", "Monge", "Montelongo", "Montemayor", "Moorman", "Moreau", "Morehead", "Moreira", "Morel", "Morrill", "Mosby", "Mosier", "Mosqueda", "Mount", "Mowery", "Moy", "Moye", "Mulder", "Mull", "Mullis", "Mundy", "Munn", "Muro", "Musser", "Nail", "Nair", "Nakamura", "Nall", "Napolitano", "Nathan", "Nation", "Neel", "Neeley", "Neill", "Nelms", "Nemeth", "Neri", "Nesmith", "Neuman", "Newland", "Nickel", "Nicolas", "Noland", "Noyes", "Null", "Nunley", "Nutt", "Nutter", "Oaks", "Ocasio", "Oden", "Ogrady", "Olds", "Olivarez", "Olivera", "Olmos", "Olmstead", "Omar", "Ong", "Ordaz", "Oropeza", "Orosco", "Orta", "Osburn", "Osman", "Ostrander", "Osuna", "Otis", "Outlaw", "Ovalle", "Oviedo", "Oxendine", "Packard", "Packer", "Pagano", "Paine", "Palacio", "Palermo", "Palm", "Palomares", "Palomino", "Palomo", "Pang", "Pannell", "Paquette", "Parada", "Parikh", "Parisi", "Parkinson", "Partida", "Partin", "Partridge", "Pastor", "Paterson", "Peace", "Peak", "Pearl", "Peebles", "Peeples", "Pelayo", "Pellegrino", "Peltier", "Pendergrass", "Perryman", "Peter", "Peterman", "Petrie", "Pettigrew", "Pettis", "Phung", "Piatt", "Piazza", "Picard", "Pickard", "Pinkerton", "Pinkston", "Pinson", "Pippin", "Pitman", "Pitt", "Pizarro", "Place", "Plante", "Plascencia", "Pleasant", "Pogue", "Pointer", "Poirier", "Poland", "Poling", "Pollack", "Pomeroy", "Pond", "Poore", "Popp", "Posada", "Prasad", "Prentice", "Prewitt", "Pride", "Proffitt", "Prosser", "Provost", "Puentes", "Puga", "Pulley", "Purnell", "Putman", "Pyles", "Quach", "Quarles", "Quesada", "Quevedo", "Raber", "Rafferty", "Rainwater", "Ralph", "Rambo", "Ramsay", "Rana", "Randazzo", "Raney", "Rash", "Rau", "Rauch", "Rausch", "Rawlings", "Raya", "Rayburn", "Raynor", "Redden", "Reddick", "Redmon", "Register", "Reimer", "Reinhart", "Reiss", "Reitz", "Renfro", "Reno", "Resendez", "Restrepo", "Reuter", "Rey", "Rhea", "Rickard", "Ricker", "Riddick", "Ridenour", "Ridge", "Ridgeway", "Ries", "Rigsby", "Rinaldi", "Riordan", "Ripley", "Ritchey", "Robinette", "Robson", "Roby", "Rodarte", "Roddy", "Roderick", "Rohrer", "Roller", "Romeo", "Romine", "Rosenbaum", "Rosenberger", "Rosser", "Rousseau", "Royster", "Ruby", "Rudy", "Rueda", "Ruggiero", "Runyon", "Rupert", "Rutter", "Sabo", "Sachs", "Saleh", "Salem", "Salerno", "Salmeron", "Samaniego", "Sammons", "Samples", "Samuelson", "Sanabria", "Sanches", "Sandberg", "Sander", "Sandhu", "Sandlin", "Santacruz", "Santoro", "Santoyo", "Sarabia", "Sasser", "Sato", "Saul", "Savoy", "Saxon", "Saxton", "Sayers", "Sayre", "Scarbrough", "Schenk", "Schiller", "Schindler", "Schlegel", "Schlosser", "Schoen", "Scholl", "Schoonover", "Schott", "Schramm", "Schreiner", "Schulze", "Scoggins", "Scroggins", "Scully", "Seal", "Seaton", "See", "Segal", "Seidel", "Seiler", "Sells", "Sena", "Servin", "Sessions", "Settle", "Sevilla", "Shade", "Shanahan", "Shane", "Sharkey", "Shay", "Sherrod", "Sherry", "Shifflett", "Shinn", "Shirk", "Shores", "Shorter", "Showalter", "Shull", "Shumaker", "Shuman", "Shumate", "Sibley", "Siddiqui", "Sides", "Sigler", "Siler", "Silvers", "Simone", "Simonson", "Sipes", "Sisco", "Slagle", "Slattery", "Slayton", "Sledge", "Slocum", "Smail", "Smoot", "Smothers", "Smyth", "Snipes", "Snook", "So", "Soliz", "Sorrell", "Southard", "Southerland", "Southern", "Sowell", "Spalding", "Sparkman", "Sparrow", "Spearman", "Speed", "Spellman", "Sperry", "Spires", "Spooner", "Spradlin", "Spriggs", "Spring", "Sprouse", "Spruill", "Spurgeon", "Stacey", "Staggs", "Stallworth", "Stamps", "Staten", "Steadman", "Steel", "Stegall", "Steinmetz", "Stephan", "Stephen", "Stidham", "Stillwell", "Stine", "Stinnett", "Storm", "Stpierre", "Strain", "Straub", "Strom", "Strother", "Stroup", "Strunk", "Stubblefield", "Stull", "Sturdivant", "Sturgeon", "Sturgill", "Sturm", "Stutzman", "Suh", "Sumpter", "Sung", "Sutter", "Swafford", "Swank", "Swearingen", "Sweat", "Swisher", "Swope", "Syed", "Szabo", "Szymanski", "Ta", "Taber", "Taft", "Taggart", "Talavera", "Talbott", "Tallman", "Tamez", "Tanaka", "Tarver", "Taveras", "Teal", "Teel", "Teixeira", "Tennant", "Tenney", "Tenorio", "Teran", "Testa", "Thames", "Thatcher", "Thibodeau", "Thiel", "Thigpen", "Thomsen", "Thornburg", "Thornhill", "Tibbs", "Tijerina", "Tiller", "Tillery", "Tilton", "Timm", "Timmerman", "Tinoco", "To", "Tobar", "Toler", "Toliver", "Tomas", "Toomey", "Toscano", "Toussaint", "Towns", "Tracey", "Trapp", "Travers", "Treadway", "Tremblay", "Trice", "Trowbridge", "Troy", "True", "Truitt", "Tu", "Tully", "Turcios", "Turnbull", "Tyree", "Ulmer", "Unruh", "Upchurch", "Upshaw", "Urias", "Urrutia", "Usher", "Utley", "Vaca", "Valente", "Valenti", "Valverde", "Vandenberg", "Vanegas", "Vanmeter", "Vanwinkle", "Vargo", "Varney", "Vaught", "Veal", "Velarde", "Verdugo", "Vetter", "Vickery", "Villalpando", "Villareal", "Voigt", "Volk", "Volpe", "Vuong", "Wadsworth", "Wainwright", "Wallen", "Wallin", "Walling", "Walz", "Warfield", "Wasson", "Weatherford", "Weed", "Wegner", "Wei", "Weidner", "Weimer", "Weinberg", "Weis", "Welborn", "Welker", "Wentworth", "Wentz", "Wertz", "Westphal", "Wheaton", "Whitcomb", "Whited", "Whitehurst", "Whiteman", "Whitlow", "Whitmire", "Whitson", "Whittle", "Whitworth", "Whyte", "Wick", "Wickham", "Wicks", "Wiese", "Wilbanks", "Wilbur", "Wild", "Wilhite", "Wilke", "Wilkie", "Wilks", "Williford", "Willson", "Wilt", "Wimberly", "Windsor", "Winfield", "Wingate", "Winstead", "Wirth", "Withrow", "Witte", "Wofford", "Wojcik", "Woodbury", "Wooden", "Woodworth", "Wooldridge", "Worden", "Worth", "Worthy", "Wozniak", "Wynne", "Xie", "Yager", "Yamamoto", "Yao", "Ye", "Yeung", "Yount", "Yuan", "Yuen", "Yun", "Zamarripa", "Zayas", "Zeng", "Zimmermann", "Zink", "Zook"]


//MARK: - Hex Colors Array

var allHexColorsArray = ["#000000","#0C090A","#34282C","#3B3131","#3A3B3C","#454545","#413839","#3D3C3A","#463E3F","#4C4646","#504A4B","#565051","#52595D","#5C5858","#625D5D","#666362","#696969","#686A6C","#6D6968","#726E6D","#736F6E","#757575","#797979","#837E7C","#808080","#848482","#8D918D","#A9A9A9","#B6B6B4","#C0C0C0","#C9C0BB","#D1D0CE","#CECECE","#D3D3D3","#DADBDD","#DCDCDC","#E5E4E2","#BCC6CC","#98AFC7","#838996","#778899","#708090","#6D7B8D","#657383","#616D7E","#646D7E","#566D7E","#737CA1","#728FCE","#4863A0","#2B547E","#36454F","#29465B","#2B3856","#123456","#151B54","#191970","#000080","#151B8D","#00008B","#15317E","#0000A0","#0000A5","#0020C2","#0000CD","#0041C2","#2916F5","#0000FF","#0909FF","#1F45FC","#2554C7","#1569C7","#1974D2","#2B60DE","#4169E1","#2B65EC","#306EFF","#157DEC","#1589FF","#1E90FF","#368BC1","#4682B4","#488AC7","#357EC7","#3090C7","#659EC7","#87AFC7","#95B9C7","#6495ED","#6698FF","#56A5EC","#38ACEC","#00BFFF","#3BB9FF","#5CB3FF","#79BAEC","#82CAFF","#87CEFA","#87CEEB","#A0CFEC","#B7CEEC","#B4CFEC","#ADDFFF","#C2DFFF","#C6DEFF","#BDEDFF","#B0E0E6","#AFDCEC","#ADD8E6","#B0CFDE","#C9DFEC","#D5D6EA","#E3E4FA","#DBE9FA","#E6E6FA","#EBF4FA","#F0F8FF","#F8F8FF","#F0FFFF","#E0FFFF","#CCFFFF","#9AFEFF","#7DFDFE","#57FEFF","#00FFFF","#0AFFFF","#50EBEC","#4EE2EC","#16E2F5","#8EEBEC","#AFEEEE","#CFECEC","#81D8D0","#77BFC7","#92C7C7","#78C7C7","#7BCCB5","#66CDAA","#AAF0D1","#7FFFD4","#93FFE8","#40E0D0","#48D1CC","#48CCCD","#46C7C7","#43C6DB","#00CED1","#43BFC7","#20B2AA","#3EA99F","#5F9EA0","#3B9C9C","#008B8B","#00827F","#008080","#045F5F","#033E3E","#25383C","#2C3539","#3C565B","#4C787E","#5E7D7E","#307D7E","#348781","#438D80","#4E8975","#306754","#2E8B57","#31906E","#00A36C","#34A56F","#50C878","#3EB489","#3CB371","#7C9D8E","#78866B","#848B79","#617C58","#728C00","#6B8E23","#808000","#556B2F","#4E5B31","#4B5320","#667C26","#4E9258","#387C44","#347235","#347C2C","#228B22","#008000","#006400","#046307","#355E3B","#254117","#437C17","#347C17","#6AA121","#4AA02C","#41A317","#12AD2B","#3EA055","#73A16C","#6CBB3C","#6CC417","#4CC417","#32CD32","#52D017","#4CC552","#54C571","#99C68E","#8FBC8F","#89C35C","#85BB65","#9CB071","#B0BF1A","#B2C248","#9DC209","#A1C935","#9ACD32","#77DD77","#7FE817","#59E817","#57E964","#16F529","#5EFB6E","#36F57F","#00FF7F","#00FA9A","#5FFB17","#00FF00","#7CFC00","#66FF00","#7FFF00","#87F717","#98F516","#B1FB17","#ADFF2F","#BDF516","#DAEE01","#E2F516","#CCFB5D","#BCE954","#64E986","#90EE90","#6AFB92","#98FB98","#98FF98","#B5EAAA","#E3F9A6","#C3FDB8","#DBF9DB","#E8F1D4","#F0FFF0","#F5FFFA","#FFFACD","#FFFFC2","#FFFFCC","#FFFDD0","#FAFAD2","#FFFFE0","#F5F5DC","#FFF8DC","#FBF6D9","#F7E7CE","#FAEBD7","#FFEFD5","#FFEBCD","#FFE4C4","#F5DEB3","#FFE4B5","#FFE5B4","#FED8B1","#FFDAB9","#FFDEAD","#FBE7A1","#F3E3C3","#F0E2B6","#F1E5AC","#F3E5AB","#ECE5B6","#E8E4C9","#EEE8AA","#F0E68C","#EDDA74","#EDE275","#FFE87C","#FFF380","#FAF884","#FFFF33","#FFFF00","#FFEF00","#F5E216","#FFDB58","#FFDF00","#F9DB24","#FFD801","#FFD700","#FDD017","#FFCE44","#EAC117","#F6BE00","#F2BB66","#FBB917","#FDBD01","#FBB117","#FFAE42","#FFA62F","#FFA500","#EE9A4D","#F4A460","#E2A76F","#C19A6B","#E6BF83","#DEB887","#D2B48C","#C8AD7F","#C2B280","#BCB88A","#C8B560","#C9BE62","#C9AE5D","#BDB76B","#BAB86C","#B5A642","#C7A317","#D4AF37","#E9AB17","#E8A317","#DAA520","#D4A017","#C68E17","#B8860B","#C58917","#CD853F","#CD7F32","#C88141","#B87333","#AA6C39","#AB784E","#966F33","#806517","#665D1E","#8E7618","#8B8000","#827839","#8A865D","#93917C","#9F8C76","#AF9B60","#827B60","#786D5F","#483C32","#493D26","#513B1C","#3D3635","#3B2F2F","#43302E","#49413F","#5C3317","#654321","#704214","#804A00","#6F4E37","#835C3B","#7F5217","#7F462C","#A0522D","#8B4513","#8A4117","#7E3817","#7E3517","#954535","#C34A2C","#C04000","#EB5406","#C35817","#B86500","#B5651D","#B76734","#C36241","#CB6D51","#C47451","#D2691E","#CC6600","#E56717","#E66C2C","#FF6700","#FF5F1F","#F87217","#F88017","#FF8C00","#F87431","#FF7722","#E67451","#FF8040","#FF7F50","#F88158","#F9966B","#FFA07A","#E9967A","#E78A61","#DA8A67","#FF8674","#FA8072","#F98B88","#F08080","#F67280","#E77471","#F75D59","#E55451","#CD5C5C","#FF6347","#E55B3C","#FF4500","#FF0000","#FD1C03","#FF2400","#F62217","#F70D1A","#F62817","#E42217","#E41B17","#DC381F","#C24641","#C11B17","#B22222","#B21807","#A52A2A","#A70D2A","#9F000F","#931314","#990000","#990012","#8B0000","#800000","#8C001A","#7E191B","#800517","#660000","#551606","#560319","#3D0C02","#3F000F","#2B1B17","#550A35","#810541","#7D0541","#7D0552","#872657","#7E354D","#7F4E52","#7F525D","#7F5A58","#997070","#B1907F","#B38481","#BC8F8F","#C5908E","#C48793","#C48189","#E799A3","#D58A94","#E8ADAA","#C4AEAD","#E6C7C2","#ECC5C0","#FFCBA4","#F8B88B","#EDC9AF","#FFDDCA","#FDD7E4","#FFE6E8","#FFE4E1","#FFDFDD","#FFCCCB","#FBCFCD","#FBBBB9","#FFC0CB","#FFB6C1","#FAAFBE","#FAAFBA","#F9A7B0","#FEA3AA","#E7A1B0","#E38AAE","#F778A1","#E56E94","#DB7093","#D16587","#C25A7C","#C25283","#E75480","#F660AB","#FF69B4","#FC6C85","#F6358A","#F52887","#FF007F","#FF1493","#F535AA","#FD349C","#E45E9D","#E759AC","#E3319D","#E4287C","#FA2A55","#E30B5D","#DC143C","#C32148","#C21E56","#C12869","#C12267","#CA226B","#CC338B","#C71585","#C12283","#B3446C","#B93B8F","#DA70D6","#DF73D4","#EE82EE","#FF77FF","#F433FF","#FF00FF","#E238EC","#D462FF","#C45AEC","#BA55D3","#A74AC7","#B048B5","#D291BC","#915F6D","#7E587E","#614051","#583759","#5E5A80","#4E5180","#6A5ACD","#6960EC","#736AFF","#7B68EE","#7575CF","#6667AB","#6F2DA8","#6C2DC7","#6A0DAD","#5453A6","#483D8B","#4E387E","#571B7E","#4B0150","#36013F","#461B7E","#4B0082","#342D7E","#663399","#6A287E","#8B008B","#800080","#86608E","#9932CC","#9400D3","#8D38C9","#A23BEC","#B041FF","#842DCE","#8A2BE2","#7A5DC7","#7F38EC","#9D00FF","#8E35EF","#893BFF","#967BB6","#9370DB","#8467D7","#9172EC","#9E7BFF","#CCCCFF","#DCD0FF","#E0B0FF","#D891EF","#B666D2","#C38EC7","#C8A2C8","#DDA0DD","#E6A9EC","#F2A2E8","#F9B7FF","#C6AEC7","#D2B9D3","#D8BFD8","#DFD3E3","#E9CFEC","#FCDFFF","#EBDDE2","#E1D9D1","#E9E4D4","#EDE6D6","#FAF0DD","#F8F0E3","#F8F6F0","#F3E8EA","#FFF0F5","#FDEEF4","#FFF9E3","#FDF5E6","#FAF0E6","#FFF5EE","#F9F6EE","#FAF5EF","#FFFAF0","#FFFFF0","#FFFFF4","#FFFFF7","#F5F5F5","#FBFBF9","#FFFAFA","#FEFCFF","#FFFFFF"]




// MARK: - Animals Array

var animalsArray = ["Aardvark","Aardwolf","African Buffalo","African Elephant","African Leopard","Albatross","Alligator","Alpaca","Amphibian","Anaconda","Angelfish","Anglerfish","Ant","Anteater","Antelope","Antlion","Ape","Aphid","Arabian Leopard","Arctic Fox","Arctic Wolf","Armadillo","Arrow Crab","Asp","Baboon","Bactrian Camel","Badger","Bald Eagle","Bali Cattle","Bandicoot","Barnacle","Barracuda","Basilisk","Bass","Bat","Beaked Whale","Bear","Beaver","Bedbug","Bee","Beetle","Bird","Bison","Black Panther","Black Widow Spider","Blackbird","Blue Bird","Blue Jay","Blue Whale","Boa","Boar","Bobcat","Bobolink","Bonobo","Bovid","Box Jellyfish","Buffalo","Bug","Butterfly","Buzzard","Camel","Canary","Canid","Canidae","Cape Buffalo","Capybara","Cardinal","Caribou","Carp","Cat","Caterpillar","Catfish","Catshark","Cattle","Centipede","Cephalopod","Chameleon","Cheetah","Chickadee","Chicken","Chimpanzee","Chinchilla","Chipmunk","Cicada","Clam","Clownfish","Cobra","Cockroach","Cod","Condor","Constrictor","Coral","Cougar","Cow","Coyote","Crab","Crane Fly","Crane","Crawdad","Crayfish","Cricket","Crocodile","Crow","Cuckoo","Damselfly","Deer","Dingo","Dinosaur","Dog","Dolphin","Donkey","Dormouse","Dove","Dragon","Dragonfly","Dromedary Camel","Duck","Dung Beetle","Eagle","Earthworm","Earwig","Echidna","Eel","Egret","Elephant Seal","Elephant","Elk","Emu","English Pointer","Ermine","Falcon","Fancy Mouse","Fancy Rat Varieties","Fancy Rat","Felidae","Ferret","Finch","Firefly","Fish","Flamingo","Flea","Fly","Flyingfish","Fowl","Fox","Frog","Fruit Bat","Galliform","Gamefowl","Gayal","Gazelle","Gecko","Gerbil","Giant Panda","Giant Squid","Gibbon","Gila Monster","Giraffe","Goat","Goldfish","Goose","Gopher","Gorilla","Grasshopper","Great Blue Heron","Great White Shark","Grizzly Bear","Ground Shark","Ground Sloth","Grouse","Guan","Guanaco","Guinea Pig","Guineafowl","Gull","Guppy","Haddock","Halibut","Hammerhead Shark","Hamster","Hare","Harrier","Hawk","Hedgehog","Hermit Crab","Heron","Herring","Hippopotamus","Hookworm","Hornet","Horse","Hoverfly","Hummingbird","Humpback Whale","Hyena","Iguana","Impala","Irukandji Jellyfish","Jackal","Jaguar","Jay","Jellyfish","Junglefowl","Kangaroo Mouse","Kangaroo Rat","Kangaroo","Kingfisher","Kite","Kiwi","Koala","Koi","Komodo Dragon","Krill","Lab Rat","Ladybug","Lamprey","Land Snail","Landfowl","Lark","Leech","Lemming","Lemur","Leopard","Leopon","Limpet","Lion","Lizard","Llama","Lobster","Locust","Loon","Louse","Lungfish","Lynx","Macaw","Mackerel","Magpie","Mammal","Manatee","Mandrill","Manta Ray","Marlin","Marmoset","Marmot","Marsupial","Marten","Mastodon","Meadowlark","Meerkat","Mink","Minnow","Mite","Mockingbird","Mole","Mollusk","Mongoose","Monitor Lizard","Monkey","Moose","Mosquito","Moth","Mountain Goat","Mouse","Mule","Muskox","Narwhal","New World Quail","Newt","Nightingale","Ocelot","Octopus","Old World Quail","Opossum","Orangutan","Orca","Ostrich","Otter","Owl","Ox","Panda","Panther","Panthera Hybrid","Parakeet","Parrot","Parrotfish","Partridge","Peacock","Peafowl","Pelican","Penguin","Perch","Peregrine Falcon","Pheasant","Pig","Pigeon","Pike","Pilot Whale","Pinniped","Piranha","Planarian","Platypus","Polar Bear","Pony","Porcupine","Porpoise","Portuguese Man O' War","Possum","Prairie Dog","Prawn","Praying Mantis","Primate","Ptarmigan","Puffin","Puma","Python","Quail","Quelea","Quokka","Rabbit","Raccoon","Rainbow Trout","Rat","Rattlesnake","Raven","Ray","Red Panda","Reindeer","Reptile","Rhinoceros","Right Whale","Ringneck Dove","Roadrunner","Robin","Rodent","Rook","Rooster","Roundworm","Saber-toothed Cat","Sailfish","Salamander","Salmon","Sawfish","Scale Insect","Scallop","Scorpion","Sea Lion","Sea Slug","Sea Snail","Seahorse","Shark","Sheep","Shrew","Shrimp","Siamese Fighting Fish","Silkmoth","Silkworm","Silver Fox","Silverfish","Skink","Skunk","Sloth","Slug","Smelt","Snail","Snake","Snipe","Snow Leopard","Society Finch","Sockeye Salmon","Sole","Sparrow","Sperm Whale","Spider Monkey","Spider","Spoonbill","Squid","Squirrel","Star-nosed Mole","Starfish","Steelhead Trout","Stingray","Stoat","Stork","Sturgeon","Sugar Glider","Swallow","Swan","Swift","Swordfish","Swordtail","Tahr","Takin","Tapir","Tarantula","Tarsier","Tasmanian Devil","Termite","Tern","Thrush","Tick","Tiger Shark","Tiger","Tiglon","Toad","Tortoise","Toucan","Trapdoor Spider","Tree Frog","Trout","Tuna","Turkey","Turtle","Tyrannosaurus","Urial","Vampire Bat","Vampire Squid","Vicuna","Viper","Vole","Vulture","Wallaby","Walrus","Warbler","Wasp","Water Boa","Water Buffalo","Weasel","Whale","Whippet","Whitefish","Whooping Crane","Wildcat","Wildebeest","Wildfowl","Wolf","Wolverine","Wombat","Woodpecker","Worm","Wren","X-ray Fish","Xerinae","Yak","Yellow Perch","Zebra Finch","Zebra",
]


var animalsArrayA = [
"Aardvark",
"Aardwolf",
"African Buffalo",
"African Elephant",
"African Leopard",
"Albatross",
"Alligator",
"Alpaca",
"Amphibian",
"Anaconda",
"Angelfish",
"Anglerfish",
"Ant",
"Anteater",
"Antelope",
"Antlion",
"Ape",
"Aphid",
"Arabian Leopard",
"Arctic Fox",
"Arctic Wolf",
"Armadillo",
"Arrow Crab",
"Asp"]

var animalsArrayB = [
"Baboon",
"Bactrian Camel",
"Badger",
"Bald Eagle",
"Bali Cattle",
"Bandicoot",
"Barnacle",
"Barracuda",
"Basilisk",
"Bass",
"Bat",
"Beaked Whale",
"Bear",
"Beaver",
"Bedbug",
"Bee",
"Beetle",
"Bird",
"Bison",
"Black Panther",
"Black Widow Spider",
"Blackbird",
"Blue Bird",
"Blue Jay",
"Blue Whale",
"Boa",
"Boar",
"Bobcat",
"Bobolink",
"Bonobo",
"Bovid",
"Box Jellyfish",
"Buffalo",
"Bug",
"Butterfly",
"Buzzard"]

var animalsArrayC = [
"Camel",
"Canary",
"Canid",
"Canidae",
"Cape Buffalo",
"Capybara",
"Cardinal",
"Caribou",
"Carp",
"Cat",
"Caterpillar",
"Catfish",
"Catshark",
"Cattle",
"Centipede",
"Cephalopod",
"Chameleon",
"Cheetah",
"Chickadee",
"Chicken",
"Chimpanzee",
"Chinchilla",
"Chipmunk",
"Cicada",
"Clam",
"Clownfish",
"Cobra",
"Cockroach",
"Cod",
"Condor",
"Constrictor",
"Coral",
"Cougar",
"Cow",
"Coyote",
"Crab",
"Crane Fly",
"Crane",
"Crawdad",
"Crayfish",
"Cricket",
"Crocodile",
"Crow",
"Cuckoo"]

var animalsArrayD = [
"Damselfly",
"Deer",
"Dingo",
"Dinosaur",
"Dog",
"Dolphin",
"Donkey",
"Dormouse",
"Dove",
"Dragon",
"Dragonfly",
"Dromedary Camel",
"Duck",
"Dung Beetle",
]
var animalsArrayE = [
"Eagle",
"Earthworm",
"Earwig",
"Echidna",
"Eel",
"Egret",
"Elephant Seal",
"Elephant",
"Elk",
"Emu",
"English Pointer",
"Ermine",
]
var animalsArrayF = [
"Falcon",
"Fancy Mouse",
"Fancy Rat Varieties",
"Fancy Rat",
"Felidae",
"Ferret",
"Finch",
"Firefly",
"Fish",
"Flamingo",
"Flea",
"Fly",
"Flyingfish",
"Fowl",
"Fox",
"Frog",
"Fruit Bat",
]
var animalsArrayG = [
"Galliform",
"Gamefowl",
"Gayal",
"Gazelle",
"Gecko",
"Gerbil",
"Giant Panda",
"Giant Squid",
"Gibbon",
"Gila Monster",
"Giraffe",
"Goat",
"Goldfish",
"Goose",
"Gopher",
"Gorilla",
"Grasshopper",
"Great Blue Heron",
"Great White Shark",
"Grizzly Bear",
"Ground Shark",
"Ground Sloth",
"Grouse",
"Guan",
"Guanaco",
"Guinea Pig",
"Guineafowl",
"Gull",
"Guppy",
]
var animalsArrayH = [
"Haddock",
"Halibut",
"Hammerhead Shark",
"Hamster",
"Hare",
"Harrier",
"Hawk",
"Hedgehog",
"Hermit Crab",
"Heron",
"Herring",
"Hippopotamus",
"Hookworm",
"Hornet",
"Horse",
"Hoverfly",
"Hummingbird",
"Humpback Whale",
"Hyena",
]
var animalsArrayI = [
"Iguana",
"Impala",
"Irukandji Jellyfish",
]

var animalsArrayJ = [
"Jackal",
"Jaguar",
"Jay",
"Jellyfish",
"Junglefowl",
]

var animalsArrayK = [
"Kangaroo Mouse",
"Kangaroo Rat",
"Kangaroo",
"Kingfisher",
"Kite",
"Kiwi",
"Koala",
"Koi",
"Komodo Dragon",
"Krill",
]

var animalsArrayL = [
"Lab Rat",
"Ladybug",
"Lamprey",
"Land Snail",
"Landfowl",
"Lark",
"Leech",
"Lemming",
"Lemur",
"Leopard",
"Leopon",
"Limpet",
"Lion",
"Lizard",
"Llama",
"Lobster",
"Locust",
"Loon",
"Louse",
"Lungfish",
"Lynx",
]
var animalsArrayM = [
"Macaw",
"Mackerel",
"Magpie",
"Mammal",
"Manatee",
"Mandrill",
"Manta Ray",
"Marlin",
"Marmoset",
"Marmot",
"Marsupial",
"Marten",
"Mastodon",
"Meadowlark",
"Meerkat",
"Mink",
"Minnow",
"Mite",
"Mockingbird",
"Mole",
"Mollusk",
"Mongoose",
"Monitor Lizard",
"Monkey",
"Moose",
"Mosquito",
"Moth",
"Mountain Goat",
"Mouse",
"Mule",
"Muskox",
]

var animalsArrayN = [
"Narwhal",
"New World Quail",
"Newt",
"Nightingale",
]
var animalsArrayO = [
"Ocelot",
"Octopus",
"Old World Quail",
"Opossum",
"Orangutan",
"Orca",
"Ostrich",
"Otter",
"Owl",
"Ox",
]
var animalsArrayP = [
"Panda",
"Panther",
"Panthera Hybrid",
"Parakeet",
"Parrot",
"Parrotfish",
"Partridge",
"Peacock",
"Peafowl",
"Pelican",
"Penguin",
"Perch",
"Peregrine Falcon",
"Pheasant",
"Pig",
"Pigeon",
"Pike",
"Pilot Whale",
"Pinniped",
"Piranha",
"Planarian",
"Platypus",
"Polar Bear",
"Pony",
"Porcupine",
"Porpoise",
"Portuguese Man O' War",
"Possum",
"Prairie Dog",
"Prawn",
"Praying Mantis",
"Primate",
"Ptarmigan",
"Puffin",
"Puma",
"Python",
]

var animalsArrayQ = [
"Quail",
"Quelea",
"Quokka",
]

var animalsArrayR = [
"Rabbit",
"Raccoon",
"Rainbow Trout",
"Rat",
"Rattlesnake",
"Raven",
"Ray",
"Red Panda",
"Reindeer",
"Reptile",
"Rhinoceros",
"Right Whale",
"Ringneck Dove",
"Roadrunner",
"Robin",
"Rodent",
"Rook",
"Rooster",
"Roundworm",
]

var animalsArrayS = [
"Saber-toothed Cat",
"Sailfish",
"Salamander",
"Salmon",
"Sawfish",
"Scale Insect",
"Scallop",
"Scorpion",
"Sea Lion",
"Sea Slug",
"Sea Snail",
"Seahorse",
"Shark",
"Sheep",
"Shrew",
"Shrimp",
"Siamese Fighting Fish",
"Silkmoth",
"Silkworm",
"Silver Fox",
"Silverfish",
"Skink",
"Skunk",
"Sloth",
"Slug",
"Smelt",
"Snail",
"Snake",
"Snipe",
"Snow Leopard",
"Society Finch",
"Sockeye Salmon",
"Sole",
"Sparrow",
"Sperm Whale",
"Spider Monkey",
"Spider",
"Spoonbill",
"Squid",
"Squirrel",
"Star-nosed Mole",
"Starfish",
"Steelhead Trout",
"Stingray",
"Stoat",
"Stork",
"Sturgeon",
"Sugar Glider",
"Swallow",
"Swan",
"Swift",
"Swordfish",
"Swordtail",
]

var animalsArrayT = [
"Tahr",
"Takin",
"Tapir",
"Tarantula",
"Tarsier",
"Tasmanian Devil",
"Termite",
"Tern",
"Thrush",
"Tick",
"Tiger Shark",
"Tiger",
"Tiglon",
"Toad",
"Tortoise",
"Toucan",
"Trapdoor Spider",
"Tree Frog",
"Trout",
"Tuna",
"Turkey",
"Turtle",
"Tyrannosaurus",
]

var animalsArrayU = [
"Urial",
]
var animalsArrayV = [
"Vampire Bat",
"Vampire Squid",
"Vicuna",
"Viper",
"Vole",
"Vulture",
]

var animalsArrayW = [
"Wallaby",
"Walrus",
"Warbler",
"Wasp",
"Water Boa",
"Water Buffalo",
"Weasel",
"Whale",
"Whippet",
"Whitefish",
"Whooping Crane",
"Wildcat",
"Wildebeest",
"Wildfowl",
"Wolf",
"Wolverine",
"Wombat",
"Woodpecker",
"Worm",
"Wren",
]
var animalsArrayX = [
"X-ray Fish",
"Xerinae",
]

var animalsArrayY = [
"Yak",
"Yellow Perch",
]

var animalsArrayZ = [
"Zebra Finch",
"Zebra",
]
